version: '0.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    env_file: .env
    environment:
      RAILS_ENV: development

  database:
    image: postgres:14.1
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: screenscms
      POSTGRES_PASSWORD: purrweb

volumes:
  gem_cache:
  db_data:
