# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_api_audience: <%= ENV["AUTH0_API_AUDIENCE"] %>

test:
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_api_audience: <%= ENV["AUTH0_API_AUDIENCE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_api_audience: <%= ENV["AUTH0_API_AUDIENCE"] %>
